### ISSUE TITLE
异步通信地址怎么填呢

### ISSUE THREAD

**Issue by luxlzz6** [ASTWY/vmq-go#1]

**Comment by ASTWY** [comment]
这取决于你对接的服务，一般来说是一个网络地址，vmq会在订单完成时向异步通信（异步回调）地址发起请求通知订单完

**Comment by luxlzz6** [comment]
> 这取决于你对接的服务，一般来说是一个网络地址，vmq会在订单完成时向异步通信（异步回调）地址发起请求通知订单完

什么时候可以加上支付宝免挂就好了

**Comment by ASTWY** [comment]
这个功能不能做
