### ISSUE TITLE
大佬 最新的代码构建报错了呢，提示缺少文件

### ISSUE THREAD

**Issue by markwhitey** [ASTWY/vmq-go#2]
18.84 [vite:load-fallback] Could not load /src/frontend/src/components/TextDisplay.vue (imported by src/views/admin/OrdersView.vue): ENOENT: no such file or directory, open '/src/frontend/src/components/TextDisplay.vue'
18.84 error during build:
18.84 Error: Could not load /src/frontend/src/components/TextDisplay.vue (imported by src/views/admin/OrdersView.vue): ENOENT: no such file or directory, open '/src/frontend/src/components/TextDisplay.vue'
18.84     at async open (node:internal/fs/promises:637:25)
18.84     at async Object.readFile (node:internal/fs/promises:1246:14)
18.84     at async PluginDriver.hookFirstAndGetPlugin (file:///src/frontend/node_modules/rollup/dist/es/shared/node-entry.js:25444:28)
18.84     at async file:///src/frontend/node_modules/rollup/dist/es/shared/node-entry.js:24611:75
18.84     at async Queue.work (file:///src/frontend/node_modules/rollup/dist/es/shared/node-entry.js:25654:32)

**Comment by ASTWY** [comment]
该错误是前端编译的问题，但是错误内容太少，我无法知道你是如何触发该错误的

**Comment by ASTWY** [comment]
该错误似乎是由我提交了错误的代码导致，你可以先使用之前发布的前端构建产物，并不影响

**Comment by ASTWY** [comment]
该问题已经解决
